### ISSUE TITLE
Examples - check_transform.py fails

### ISSUE THREAD

**Issue by FollowingGhosts** [CryptoCredits/credits-common#20]
Running Windows 10 x64 with Python 3.6.0
Code is checked out from repo as-is. Same error exists with newer versions on other branches of this repo.

Any advice on how to fix it would be appreciated.

Error received is as follows:
```
Traceback (most recent call last):
  File "check_transform.py", line 41, in <module>
    state_expected=state_expected,
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python36-32\lib\site-packages\credits\test.py", line 65, in check_transform
    result, error = transform.verify(deepcopy(state))
  File "C:\Users\Ben\PycharmProjects\credits_test\balance_transform.py", line 39, in verify
    state="credits.test.Balances",
Exception: alice_address not in credits.test.Balances
```

**Comment by alexykot** [comment]
Can you provide the state.json you're trying it with? It may be the case that you've not provided fully correct genesis state for it.
